### PR TITLE
Dj/responsive frontpage banner

### PR DESCRIPTION
**Pull request by hjdjoo**
WHEN a user navigates the front page
AND the user hovers over the banner/nav buttons,
THEN the buttons should behave with responsiveness.
AND WHEN a user resizes the window,
THEN the images and banners should smoothly resize.
AND WHEN a user hovers over product images,
THEN the cursor should change to a pointer.
AND WHEN a user clicks on the other category headers,
THEN the carousel for each category should be toggled.

### CODE REVIEW

**Comment by echochs1** [comment]
The carousel navigation buttons need more emphasized responses to hover imo as well as the hover effects over product cards. The window size has to be adjusted for Windows users to account for the Windows scrollbar. Personally, I dont reallly like the toggled carousels but that is just my preference.

**Comment by echochs1** [comment]
Quick update, the side scrollbar on the website shows up on my Windows desktop even on other branches. The issue that I see is that the banner-spacer div in particular is too big. 

Here is a screenshot of the body element and you can see that there is a white space evenly throughout the right side of the website and the console. 
Screenshot (119)

And here is the screenshot of the banner-spacer div. The blue highlighted area is next to the console without any white space in between. 
Screenshot (118)

**Comment by hjdjoo** [comment]
@echochs1 The current version should actually not have the banner spacer at all - is the side-scrollbar issue still there?

Re: toggled carousels - I was thinking about what the front page will eventually look like with future additions - didn't want it to feel too messy after we add things like promo text and such. Can easily remove it at any point down the line, so I will keep note

**Comment by hjdjoo** [comment]
@echochs1 Added final changes/adjustments if you wanna take a look and merge

**Pull request merged**
